# Generated by Django 4.1.12 on 2023-10-19 16:28

import Taskify_App.utils
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(blank=True, choices=[('h', 'high'), ('m', 'medium'), ('l', 'low')], max_length=1, null=True)),
                ('is_resolved', models.BooleanField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('wiki', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('year1_visibility', models.BooleanField(default=True)),
                ('year2_visibility', models.BooleanField(default=True)),
                ('year3_visibility', models.BooleanField(default=True)),
                ('year4_visibility', models.BooleanField(default=True)),
                ('year5_visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('a', 'admin'), ('n', 'normal_user')], default='n', max_length=1)),
                ('email', models.EmailField(max_length=60)),
                ('enrollment_no', models.BigIntegerField(unique=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'unique_together': {('name', 'enrollment_no')},
            },
        ),
        migrations.CreateModel(
            name='Project_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('l', 'leader'), ('m', 'member')], max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskify_App.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskify_App.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(related_name='projects', to='Taskify_App.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField()),
                ('redirection_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Taskify_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskify_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(default=Taskify_App.utils.generate_unique_colour, max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='Taskify_App.project')),
            ],
            options={
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Taskify_App.user')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Taskify_App.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='assignees',
            field=models.ManyToManyField(to='Taskify_App.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Taskify_App.list'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('title', 'list')},
        ),
    ]
