# Generated by Django 4.1.12 on 2023-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskify_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
