# Generated by Django 4.1.12 on 2023-11-29 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Taskify_App', '0003_alter_user_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
