# Generated by Django 4.1.12 on 2023-12-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskify_App', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
