# Generated by Django 4.1.12 on 2023-12-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskify_App', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['id']},
        ),
    ]
